services:
  skedge-api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command:
      ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/app.ts"]
